### ISSUE TITLE
Add map and display all surrounding bars

### ISSUE THREAD

**Issue by augisjay** [joklek/BeerOverflowWindowsApp#28]

**Comment by joklek** [comment]
For now we can use Google Static API to fetch an image of the bar and display it.
How to use the code [here](https://stackoverflow.com/questions/11594702/how-to-get-image-from-google-static-map-api), and documentation [here](https://developers.google.com/maps/documentation/static-maps/intro). There are probably other solutions too.

**Comment by augisjay** [comment]
Hey! Some of you've already heard that problem I have. So the issue is that I don't know where to get bars' locations after the list is created. I get the feeling, that after search and distance to user count they just disappear and there are saved only those, which were rated during program run. For pushpins I need to make a list of bars info, which would include Latitude,Longitude, bar name and bar rating. Any help and ideas?

**Comment by augisjay** [comment]
I believe there will be a problem to show google images on BING map, you know. Maybe later I could see what is possible to be done with that, but for now I just need to understand, where is the info about all the bars AFTER the list is shown, because i need to send it to the map. On the other hand i could create a method, that creates a list and keeps it while program is running and use it for my map, but i think that's an unnecessary waste of resources and time...

**Comment by joklek** [comment]
All the bar information is saved in MainWindow _barRating.BarsData, it's a list of bars. The bars themselves hold their location info and distance to the user
