### ISSUE TITLE
Bug: Crash when ManualBarRating tries to show tooltips outside the window

### ISSUE THREAD

**Issue by joklek** [joklek/BeerOverflowWindowsApp#32]
#### Issue description

Program crashes when clicking on ManualBeerRating panel and dragging the out of the panel while the mouse is still held down.

#### Steps to reproduce the issue

1.  Open program.
2.  Mouse Down on ManualBeerRating the last beer.
3.  Leave panel through the right side.

Alternatively

1.  Open program.
2.  Mouse Down on ManualBeerRating the first beer.
3.  Leave panel through the left side.

#### What's the expected result?

Not crashing, not showing any tooltips when leaving ManualBeerRating panel.

#### What's the actual result?

Crash.
`An unhandled exception of type 'System.IndexOutOfRangeException' occurred in BeerOverflowWindowsApp.exe
Index was outside the bounds of the array.`

at ManualBeerRating.cs line 98, method ManualBarRating_MouseMove

`toolTip.Show(toolTipMessages[lastLocation], this, e.X + 10, e.Y + 10, 3000);`

#### Additional details / screenshot

![Screenshot](https://i.imgur.com/1qYtnkJ.png)

**Comment by DomantasDev** [comment]
On it.

**Comment by joklek** [comment]
fixed in #34.
