### ISSUE TITLE
Sorting by distance sometimes doesn't work properly

### ISSUE THREAD

**Issue by joklek** [joklek/BeerOverflowWindowsApp#37]
I've played around on the current main, last commit to it was #33.
I reverted some commits to find which one caused this, but could not find the culprit. I went as back as the implementation of sorting by distance and I think the bug was already there.

My testing methodology is to take the first not working coords and sort. The first bars on one or another end should be Gringo, Piano Man, La Birra. I might be wrong on this, please test yourself, if you decide to fix this.

EDIT:
It is caused by CurrentLocation and it sorts by the location of the default coordinates.

### Examples of data where sorting by distance seems to work
lat: 54.684815 lon: 25.288464 radius: 150, this is the default case

### Examples of data where sorting by distance doesn't work
lat: 54.684250 lon: 25.278963 radius: 150
lat: 54.686911 lon: 25.280938 radius 150

## Screenshot of bug in action

 ![Example](https://i.imgur.com/YeM3ZWi.png)

**Comment by joklek** [comment]
Was caused by CurrentLocation class. Temp fix in #38, but I can see that @CactusGreen is working on a proper solution

**Comment by CactusGreen** [comment]
This can probably be closed now.
